services:
  mysql8:
    image: mysql:8.4
    container_name: mysql8
    restart: unless-stopped
    env_file: .env
    volumes:
      - oracle8:/var/lib/mysql
      - /etc/mysql-cont:/etc/mysql/conf.d
      - /home/db/dbinit:/docker-entrypoint-initdb.d
    networks:
      - app-network
    ports:
      - "3307:3306"
  maria11:
    image: mariadb:11.4
    container_name: maria11
    restart: unless-stopped
    env_file: .env
    volumes:
      - maria11:/var/lib/mysql
      - /etc/maria-cont:/etc/mysql/conf.d
      - /home/db/dbinit:/docker-entrypoint-initdb.d
    networks:
      - app-network
    ports:
      - "3308:3306"
  ps:
    image: percona/percona-server:8.4
    container_name: ps
    restart: unless-stopped
    env_file: .env
    volumes:
      - percona8:/var/lib/mysql
      - /etc/percona-cont:/etc/my.cnf.d
      - /home/db/dbinit:/docker-entrypoint-initdb.d
    networks:
      - app-network
    ports:
      - "3309:3306"
volumes:
  oracle8:
  maria11:
  percona8:
networks:
  app-network:
    driver: bridge